# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

workspace './Tinkoff-Contest.xcworkspace'

target 'Tinkoff-Contest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TinkoffContest', path: './../'

end
